// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	mongo "go.mongodb.org/mongo-driver/mongo"

	options "go.mongodb.org/mongo-driver/mongo/options"
)

// MongoCollection is an autogenerated mock type for the MongoCollection type
type MongoCollection struct {
	mock.Mock
}

// FindOne provides a mock function with given fields: ctx, filter, opts
func (_m *MongoCollection) FindOne(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions) *mongo.SingleResult {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *mongo.SingleResult
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOneOptions) *mongo.SingleResult); ok {
		r0 = rf(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}

	return r0
}

type mockConstructorTestingTNewMongoCollection interface {
	mock.TestingT
	Cleanup(func())
}

// NewMongoCollection creates a new instance of MongoCollection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMongoCollection(t mockConstructorTestingTNewMongoCollection) *MongoCollection {
	mock := &MongoCollection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
