// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/laenur/simple-login/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: user
func (_m *UserRepository) Delete(user entity.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: searchUsername, page, pageSize, sort, sortBy
func (_m *UserRepository) Find(searchUsername *string, page int, pageSize int, sort string, sortBy string) ([]entity.User, error) {
	ret := _m.Called(searchUsername, page, pageSize, sort, sortBy)

	var r0 []entity.User
	if rf, ok := ret.Get(0).(func(*string, int, int, string, string) []entity.User); ok {
		r0 = rf(searchUsername, page, pageSize, sort, sortBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*string, int, int, string, string) error); ok {
		r1 = rf(searchUsername, page, pageSize, sort, sortBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: userID
func (_m *UserRepository) FindByUserID(userID int64) (entity.User, error) {
	ret := _m.Called(userID)

	var r0 entity.User
	if rf, ok := ret.Get(0).(func(int64) entity.User); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: user
func (_m *UserRepository) Save(user *entity.User) (entity.User, error) {
	ret := _m.Called(user)

	var r0 entity.User
	if rf, ok := ret.Get(0).(func(*entity.User) entity.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
